"""empty message

Revision ID: 111f12be1b75
Revises: 1a3c4ef58a93
Create Date: 2026-01-15 12:10:31.836266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '111f12be1b75'
down_revision = '1a3c4ef58a93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('size_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['size_id'], ['product_size.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('size_image')
    # ### end Alembic commands ###
