"""empty message

Revision ID: 1a3c4ef58a93
Revises: 3349144395e2
Create Date: 2026-01-15 11:44:43.010549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a3c4ef58a93'
down_revision = '3349144395e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_size', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_size', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
