"""Add juice columns

Revision ID: 26c66d4ce8ed
Revises: 
Create Date: 2026-01-04 14:43:23.038391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26c66d4ce8ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_juice', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('juice_flavors', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('juice_nicotine', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('juice_nicotine')
        batch_op.drop_column('juice_flavors')
        batch_op.drop_column('is_juice')

    # ### end Alembic commands ###
