"""empty message

Revision ID: d0762de98f37
Revises: 903b9dbf44fd
Create Date: 2026-01-12 10:12:59.416453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0762de98f37'
down_revision = '903b9dbf44fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('juice_nicotine')
        batch_op.drop_column('loyverse_id')
        batch_op.drop_column('juice_flavors')
        batch_op.drop_column('is_juice')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_juice', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('juice_flavors', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('loyverse_id', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('juice_nicotine', sa.VARCHAR(length=500), nullable=True))

    # ### end Alembic commands ###
