"""empty message

Revision ID: f3d8247dd5df
Revises: bc8801745d30
Create Date: 2026-01-12 11:01:29.810980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3d8247dd5df'
down_revision = 'bc8801745d30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_size', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_size', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
